# Generated by Django 5.0.3 on 2024-03-30 17:27

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docfile",
            name="file_path",
        ),
        migrations.AddField(
            model_name="docfile",
            name="file",
            field=models.FileField(
                default="",
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to="docfiles/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="docfile",
            name="file_name",
            field=models.CharField(max_length=250),
        ),
    ]
