# Generated by Django 5.0.3 on 2024-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_docfile_file_path_docfile_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="framework",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
