# Generated by Django 5.0.3 on 2024-03-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_framework_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docfile",
            name="token_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
