# Generated by Django 5.0.3 on 2024-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_docfile_token_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="docfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2024-03-31T10:16:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docfile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
