# Generated by Django 5.0.3 on 2024-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_docfile_created_at_docfile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
